# Generated by Django 5.2.4 on 2025-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.URLField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
