# Generated by Django 5.2.4 on 2025-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portfolioitem_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfoliopage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
