# Generated by Django 5.2.3 on 2025-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_portfoliopage_delete_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='die_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='works/')),
            ],
        ),
    ]
