# Generated by Django 5.2.3 on 2025-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
