# Generated by Django 5.2.4 on 2025-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_certificate_description_alter_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='die_shop',
            name='description',
            field=models.TextField(default='delete'),
            preserve_default=False,
        ),
    ]
