# Generated by Django 5.2.4 on 2025-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_die_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='info',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='delete'),
            preserve_default=False,
        ),
    ]
