# Generated by Django 5.2.4 on 2025-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_remove_offer_info_offer_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("author", models.CharField(blank=True, max_length=255)),
                ("images", models.TextField(blank=True)),
            ],
        ),
    ]
