# Generated by Django 5.2.3 on 2025-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_telegrampost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramPost',
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
