# Generated by Django 5.2.3 on 2025-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_telegrampost_teammember_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
