# Generated by Django 5.2.3 on 2025-08-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_teammember_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='image',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.portfoliopage')),
            ],
        ),
    ]
