# Generated by Django 5.2.3 on 2025-08-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_portfoliopage_image_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
