# Generated by Django 5.2.3 on 2025-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_portfoliopage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='die_shop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
