# Generated by Django 5.2.3 on 2025-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_die_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
