# Generated by Django 5.2.3 on 2025-08-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_offer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
    ]
