# Generated by Django 5.2.3 on 2025-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_die_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die_shop',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
