# Generated by Django 5.2.3 on 2025-08-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_die_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='die_shop',
            name='slug',
        ),
    ]
