# Generated by Django 5.2.3 on 2025-08-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_die_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to='offers/'),
        ),
    ]
