# Generated by Django 5.2.3 on 2025-08-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_offerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to='works/gallery/'),
        ),
    ]
