# Generated by Django 5.2.3 on 2025-08-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_offerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='die_shop',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
