# Generated by Django 5.2.3 on 2025-08-19 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_die_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die_shop',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
