# Generated by Django 5.2.3 on 2025-08-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_servicepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='accordion_desc',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='accordion_title',
        ),
        migrations.CreateModel(
            name='ServiceAccordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accordion_title', models.CharField(max_length=200)),
                ('accordion_desc', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordions', to='myapp.servicepage')),
            ],
        ),
    ]
