# Generated by Django 5.2.3 on 2025-08-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_servicepage_accordion_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='subdescription',
        ),
    ]
