# Generated by Django 5.2.3 on 2025-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
    ]
